### ISSUE TITLE
A few modules need to have scripts renamed to the new moduleset_module_stage.py format (and pipeline.yml updated accordingly)

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#137]
In particular, the naming ipccar6, kopp14, larmip, NZInsarGPS, ssp, and tlm module sets have not been updated. This does not affect functionality.

**Comment by AlexReedy** [comment]
This is done, I just need to push it eventually

**Comment by AlexReedy** [comment]
Wanted to update this with a note and say that unfortunately this does seem to affect functionality. It would appear the module names (at least for the coulping.ssp585 experiment) are hardcoded somewhere in there and so changing the module names in modules directory looks like it will need it to be changed across other scripts as well. At least that is the error I am getting. Had you encountered this when you made changes to the other modules?
