### ISSUE TITLE
run_moduletest.sh is not working due to missing softlinks in module data subdirectories

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#148]
After updating the repository, `run_moduletest.sh` is failing for most of the modules. The error occurs in the preprocessing script of the given module and is due to missing data files. For example, the script `tlm_preprocess_oceandynamics.py` exits with an error 
```
FileNotFoundError: [Errno 2] No such file or directory
```
occurring when the script tries to access a file at the path `./cmip6/zos`.

I noticed that after the latest pull request, the softlinks to the `module-data` files are removed from the `/data` subdirectory for the given module, which leads to the files in `module-data` to be absent in the working directory. Regenerating the softlinks seems to fix the issue, but this needs to be done for each of the modules separately. Before I go through each module and regenerate the softlinks I want to check whether the testing of modules via `run_moduletest.sh` is still supported in the current version of FACTS. If so, I am wondering if there is a quicker way to regenerate all the softlinks at once (instead of going through each module separately)?

In the event that the use of `run_moduletest.sh` is retiring, is there a way for users to test a single module outside of FACTS? I think this would be helpful for those who are developing new modules to add into the FACTS framework.

**Comment by bobkopp** [comment]
We haven't been maintaining this functionality but I agree it would be useful. IMO it should be implemented in EnTK AppManager (see https://github.com/radical-collaboration/facts/issues/81) but if that is not in the cards, we could add code in runFACTS.py to translate the EnTK specifications into a shell script.

@andre-merzky could you please advise on plans here?

**Comment by bobkopp** [comment]
In the linked pull request, I've added some basic functionality to replace the module test scripts while being more aligned with the overall spirit of the FACTS Manager. Using the runFACTS2shell branch, the preferred replacement approach should be:

1. Create a single-module experiment config invoking the desired modules (e.g., ```experiments/onemodule```)
2. run ```python runFACTS.py --shellscript experiments/onemodule > test.sh```
3. ```source test.sh```

File handling is limited at the moment (the copy_input_data and copy_output_data commands in the pipeline.yml files are ignored), so this will work best with one-module experiment configs and probably won't work if applied to a typical multi-step experiment.

@jetesdal Could you let me know if this addresses your need?

**Comment by jetesdal** [comment]
Thank you @bobkopp for the suggestion. I will look into this and see if the proposed method will work for my needs. After running some tests, I should've a better idea about the approach and can let you know if I have any further questions or feedback.

**Comment by jetesdal** [comment]
In testing #150, I am encountering an error when the module relies on `location.lst`. Ideally, the location file can be created as in `runFACTS.py`
```
# Load the localization list
if not os.path.isfile(os.path.join(exp_dir, "location.lst")):
    print ('location.lst is missing')
    with open(os.path.join(exp_dir, "location.lst"), 'w') as templocationfile:
        templocationfile.write("New_York\t12\t40.70\t-74.01")
```

However, even if `location.lst` is created in the `experiments/onemodule` the test run fails because the `test.sh` script misses a command to copy `location.lst` to the working directory. Either the `print_experimentsteps_script()` function needs to be called in `runFACTS.py` after the lines above (`# Load the localization list`) or it might be possible to create it within `print_experimentsteps_script()`.
