### ISSUE TITLE
Unable to run `python3 runFACTS.py experiments/dummy`

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#149]
I followed the instruction in the [README](https://github.com/radical-collaboration/facts/blob/main/README.md) for installing and using FACTS. I am using FACTS on the Amarel cluster and followed the third option for setting up and launching the MongoDB server: 
> Set up your resource file to use the MongoDB server run by RADICAL. Ask for MongoDB parameters by writing to the FACTS team via email or by opening an issue in this repository.

I received the resource file  (`resource_amarel.yml`) from @pkjr002 and save it in `/facts/resources`. When trying to run
```
python3 runFACTS.py experiments/dummy
```
I get an error with the following output:
```
EnTK session: re.session.amarel1.amarel.rutgers.edu.jt1187.019361.0000
Creating AppManagerSetting up RabbitMQ system                                 ok
Traceback (most recent call last):
  File "/home/jt1187/miniconda3/envs/facts/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 567, in _setup_mqs
    mq_connection = pika.BlockingConnection(self._rmq_conn_params)
  File "/home/jt1187/miniconda3/envs/facts/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/home/jt1187/miniconda3/envs/facts/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 416, in _process_io_for_connection_setup
    self._flush_output(self._opened_result.is_ready,
  File "/home/jt1187/miniconda3/envs/facts/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 471, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
pika.exceptions.ConnectionClosed: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cache/home/jt1187/facts/runFACTS.py", line 155, in <module>
    run_experiment(args.edir, args.debug, resourcedir=args.resourcedir)
  File "/cache/home/jt1187/facts/runFACTS.py", line 67, in run_experiment
    amgr = AppManager(autoterminate=False)
  File "/home/jt1187/miniconda3/envs/facts/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 134, in __init__
    self._setup_mqs()
  File "/home/jt1187/miniconda3/envs/facts/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 601, in _setup_mqs
    raise ree.EnTKError(ex) from ex
radical.entk.exceptions.EnTKError: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
```

Is there a solution to this problem? Could the parameters in `resource_amarel.yml` need to be updated?

**Comment by bobkopp** [comment]
See resources/resource_remote_example.yml as an example of current preferred structure.

**Comment by jetesdal** [comment]
Hi @bobkopp! Thank you for your quick response and help with my issue with runFACTS.py. I have followed your suggestions and made sure my environment is set up according to the latest instructions in the README and that I am using the most recent version of the code. I have also made sure the structure of my `resource_amarel.yml` file is the same as in `resource_remote_example.yml`, and removed the RabbitMQ section. Instead of replacing `resource.yml`, I added `rcfg-name: "amarel"` as global-options in the `config.yml` file within `experiments/dummy/`.

However, I am still having issues successfully completing the test by running the dummy experiment:
```
python3 runFACTS.py experiments/dummy
```

The test run does not seem to complete as I do not get any nodes from SLURM. The standard out is stuck at:

```
EnTK session: re.session.amarel2.amarel.rutgers.edu.jt1187.019362.0000
Creating AppManagerSetting up ZMQ queues ok
ok
Validating and assigning resource manager ok
****** STEP: sealevel_step ******
Setting up ZMQ queues ok
new session: [re.session.amarel2.amarel.rutgers.edu.jt1187.019362.0000]
database : [mongodb://facts:****@95.217.193.116:27017/facts] ok
create pilot manager ok
submit 1 pilot(s)
pilot.0000 rutgers.amarel 16 cores 0 gpus ok
```

It does not seem to me that there is a lack of available cores since I am able to run other scripts via `sbatch` and OnDemand sessions are starting with little waiting time. I am not sure what the issue could be. Is there any way to check the resource manager's log files or any other suggestions for troubleshooting this issue?

**Comment by bobkopp** [comment]
Try reducing the number of cpus and hours requested (say to 1 cpu for 30 min) - that should reveal if it’s a simple resource availability issue. Otherwise will need @andre-merzky's help. I've done clean installs on Amarel a dozen times, so it's probably something particular to your account permissions (can you confirm access to the kopp_1 partition)?

**Comment by jetesdal** [comment]
I have the same problem with 1 cpu and much shorter time requirements. I am also pretty sure that I have access to kopp_1. I have been able to submit jobs to the SLURM batch scheduler using the kopp_1 partition, and the time it took for those jobs to start running was within an hour at most.

**Comment by bobkopp** [comment]
@andre-merzky @mturilli Any ideas? I confirmed with a clean install on Amarel that things are working for me.

**Comment by jetesdal** [comment]
Also @pkjr002, could you try if it it works for you? I think it was not working for you back in December, but with the latest updates it might work for you.

**Comment by jetesdal** [comment]
Hi @pkjr002! Thanks for trying to reproduce my issue. I have followed the README, which I see is now part of the readthedocs site. Would you mind sharing the error you initially encountered? Is it the same that I described above (output freezing at line pilot.0000 rutgers.amarel 16 cores 0 gpus ok)?
What is the output after successfully running 
`python3 runFACTS.py experiments/dummy`?
