### ISSUE TITLE
Temperature samples are being randomized by some sea level modules

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#159]
Some sea level modules are resampling temperature and OHC in a random fashion that  originally made sense but no longer does. Temperature sample indexing should be preserved through to total GMSL. This issue likely exists in:

- [x] FittedISMIP/GrIS
- [x] tlm/sterodynamics
- [x] IPCCAR5/glaciers
- [ ] IPCCAR5/icesheets
- [x] larmip/AIS

It does not appear to exist with emulandice, but this should be verified. 

This was not an issue in AR6 since we were not attempting to preserve traceability to individual temperature samples: 

1) For the warming-level based projections, temperature samples were filtered based on end-of-century temperature before the projection step. 

2) The modules that randomly resampled the temperature samples all did so using the same RNG seed.

**Comment by bobkopp** [comment]
fair_correlation seems to successfully fix this issue for tlm/sterodynamics and FittedISMIP/GrIS. Currently does not attempt ipccar5/* and larmip/AIS needs attention.

**Comment by bobkopp** [comment]
From Jonah Gilbert, looking at the fair_correlation branch for tlm/sterodynamics and FittedISMIP/GrIS:

### tlm/oceandynamics

![download (1)](https://user-images.githubusercontent.com/1254032/217917193-a806368a-8592-4f21-9698-eac372f93744.png)
![download](https://user-images.githubusercontent.com/1254032/217917217-f0d13c39-7a3c-4685-a9a0-1fc149436a73.png)

### FittedISMIP/GrIS

![download_480](https://user-images.githubusercontent.com/1254032/217917417-e0249e12-c19d-47a4-8c66-d9e812064c91.png)
![download_480-1](https://user-images.githubusercontent.com/1254032/217917434-8330e08c-00fd-4e71-a77c-79187fdd6cd5.png)

**Comment by bobkopp** [comment]
For LARMIP/AIS, the correlation coefficient changes from 0.02 to 0.15. This may be as expected, but it is worth double checking. The branched version of larmip_project_icesheet is (1) taking number of requested samples (= number of climate samples), (2) dividing by number of available ice sheet models, (3) chunking the available temperature trajectories sequentially (so the first samps_per_model are paired with ice sheet model 1, etc.).  I think this should be a reasonable thing to do as long as the temperature trajectories are in a random order, but it might be nice to look at the _preprocess.pkl file and inspect.

### larmip/AIS
![download_480-2](https://user-images.githubusercontent.com/1254032/217917751-8310c23b-65f4-4ca5-ab23-c02f4124fc01.png)
![download_480-3](https://user-images.githubusercontent.com/1254032/217917784-61a20a8d-c195-4695-b29d-441c1521d4b3.png)

**Comment by bobkopp** [comment]
On IPCCAR5/*, I have not made the key changes yet, The projection is currently working off of temperature (or integrated temperature) mean and standard deviation; this should be changed to working with individual samples.

**Comment by AlexReedy** [comment]
Ok, thanks Bob, I'll look into this

**Comment by bobkopp** [comment]
This discussion suggests some additional conditional distribution figures it would be useful to include in the revision of the GMD manuscript:

- [ ] a 4-panel figure showing, for each of the four focal workflows, the relationship between 2081-2100 average GSAT and 2100 GMSL. Most likely, one want to show small, faint symbols (differing by emissions scenario), plus darker bars and whiskers showing medians and quantiles (say 17-83rd with bar and 5-95 with whisker) for 0.5°C width bins centered at 1.5, 2.0, etc.
- [ ] a similar 4-panel figure for NYC RSL
- [ ] a 4-panel figure (or possible a 1-panel figure) showing the distribution of NYC RSL in 2100 as a function of GMSL in 2100 (pointing toward the filtering approach used in Sweet et al. 2022)

**Comment by bobkopp** [comment]
Given the minor revisions requested by the reviewers, these figures will not go into the paper, but we should prepare a FACTS 1.1 preprint that describes the application of FACTS to novel scenarios and includes these figures. @AlexReedy

**Comment by bobkopp** [comment]
In https://github.com/radical-collaboration/facts/edit/fair_correlation/modules/ipccar5/glaciers/ipccar5_glaciers_project.py the following:

```

	# Divide "nsamps" into "nmsamps" and "ntsamps" if necessary
	if nsamps is None:
		nsamps = nmsamps * ntsamps
	else:
		temp = int(np.ceil(np.sqrt(nsamps)))
		nmsamps = int(temp - (temp % len(glparm)))
		ntsamps = int(np.ceil(nsamps / nmsamps))

	# Generate perfectly correlated samples
	z=np.random.standard_normal(ntsamps)[:,np.newaxis]

	# For each quantity, mean + standard deviation * normal random number
	zit=inttemp_mean + (inttemp_sd * z)
```

such that z and zit are not resampled but directly taken from `temp_samples` and `inttemp_samples`, and the matching of number of samples is handled as in https://github.com/radical-collaboration/facts/blob/fair_correlation/modules/larmip/AIS/larmip_icesheet_project.py, with `len(glparm)` taking the place of `nmodels` in:

```

	# Number of models
	nmodels = len(models)

	# Set the rng seed
	rnd.seed(seed)

	# How many samples per model?
	samps_per_model = np.array([nsamps // nmodels for x in range(nmodels)])
	remainder_samps = nsamps % nmodels
	samps_per_model[rnd.sample(range(nmodels), k=remainder_samps)] += 1
	rnd.shuffle(samps_per_model)
```

and then going on to make sure, as in the LARMIP module, that the assignment of samples to models are random and not sequential.

Similar fixed needed in https://github.com/radical-collaboration/facts/blob/fair_correlation/modules/ipccar5/icesheets/ipccar5_icesheets_project.py.

**Comment by bobkopp** [comment]
Actually, you could make the change smaller by randomly sampling `ntsamps` rows of `inttemp_samps` and using those time series.

**Comment by bobkopp** [comment]
Note that the current code uses all the models with all the regenerated from mean and std temperature samples, where total number of samples is the product of number of models and number of regenerated temperature samples, while the adjusted approach needs to use all the original temperature samples, with a balanced random assignment to models (so only one model per temperature sample)

**Comment by bobkopp** [comment]
@AlexReedy what is the status of this?

**Comment by AlexReedy** [comment]
For an experiment with nsamps=2000 you have two dataframes, temp_samples and inttemp_samples. Where you have 2000 data sets (ensembles I think the code calls them) each of length 296 where each element is a temperature at a year between 2005 and 2301. 

Originally it used the mean or the sd of those data sets which flattens the temp_samples and inttemp_samples arrays to be of shape 296 where each element is the mean or sd of temperatures across 296 years.

So we're going through 2000 sets of 296 temperatures and assigning glacier models evenly across them. When this finishes do we want to flatten the array to the mean and sd again? If not I am unsure on what to do after doing the assignment

**Comment by AlexReedy** [comment]
evenly distributed or as we discussed randomly assigned, which needs to be tested.

**Comment by AlexReedy** [comment]
Right ok, also want to double check this: for determining the number of temp_samples per glacier method 

`samps_per_model = np.array([nsamps // ngl for x in range(ngl)])
remainder_samps = nsamps % ngl
samps_per_model[rnd.sample(range(ngl), k=remainder_samps)] += 1
rnd.shuffle(samps_per_model)`

In the case of nsamps =2000 this would output something like 
samps_per_model = [286 285 285 286 286 286 286]

But since we're using the unflattened samples arrays we should be using either the length of the individual temp_samples elements or the overall number of years right? Because we're not assigning 1 method to say temp_samples[i], we are applying all 7 methods evenly across temp_samples[i]

So does something like this make sense
`samps_per_model = np.array([nyr // ngl for x in range(ngl)])
remainder_samps = nyr % ngl
samps_per_model[rnd.sample(range(nyr), k=remainder_samps)] += 1
rnd.shuffle(samps_per_model)`

Which would output something like this
samps_per_model = [42 42 42 43 42 42 43]

**Comment by bobkopp** [comment]
@AlexReedy No, I think there's a miscommunication here. Each `temp_samples[i]` should have one unique glacier model assigned to it. The 'evenness' is across the ensemble of temperature samples, not across a single time series, for which switching glacier models would make no physical sense -- that's like switching model physics mid-run.

**Comment by AlexReedy** [comment]
Ah, yes there was a miscommunication, this makes way more sense

**Comment by bobkopp** [comment]
Updated list of figures:

- [ ]  a 4-panel figure showing, for each of the four focal workflows, the relationship between 2081-2100 average GSAT and 2100 GMSL. Most likely, one want to show small, faint symbols (differing by emissions scenario), plus darker bars and whiskers showing medians and quantiles (say 17-83rd with bar and 5-95 with whisker) for 0.5°C width bins centered at 1.5, 2.0, etc.
- [ ] a similar 4-panel figure for global projections from each temperature-driven module listed in manuscript Table 1 as temperature (or ocean heat content) driven
- [ ] a similar 4-panel figure for NYC RSL
- [ ] a 4-panel figure (or possible a 1-panel figure) showing the distribution of NYC RSL in 2100 as a function of GMSL in 2100 (pointing toward the filtering approach used in Sweet et al. 2022)

Let's places these figures in a short Overleaf LaTeX doc with minimalistic text for now.

**Comment by bobkopp** [comment]
This bug is addressed by the following pull requests:

- larmip/AIS: https://github.com/radical-collaboration/facts/pull/223
- tlm/sterodynamics: https://github.com/radical-collaboration/facts/pull/222
- FittedISMIP/GrIS: https://github.com/radical-collaboration/facts/pull/221
- ipccar5/glaciers: https://github.com/radical-collaboration/facts/pull/220

For each pull request, @AlexReedy needs to produce plots to verify these have been correctly addressed. 
ipccar5/icesheets also needs to be addressed.
