### ISSUE TITLE
Provide notebooks for generating p-boxes

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#165]
Many users may wish to combine the output of different workflows in p-boxes, following the practice of AR6. Notebooks should be written to make this easier to do.

**Comment by bobkopp** [comment]
This request is also needed to address Reviewer 1 confusion about how FACTS output relates to the p-boxes presented in AR6.

**Comment by bobkopp** [comment]
@pkjr002 @AlexReedy Checking on the status of this.

**Comment by pkjr002** [comment]
@bobkopp I am working on a notebook for converting FACTS output to p-boxes, will plan to share before weekend.
