### ISSUE TITLE
Flexible input of model data for ocean dynamic projections (tlm/sterodynamics)

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#167]
Currently, the tlm/sterodynamics module uses specific variables (`tas`, `zos`, and `zostoga`) from a fixed set of CMIP6 models (see Table A1 in [EGUsphere Preprint](https://egusphere.copernicus.org/preprints/2023/egusphere-2023-14/)). The model output are provided as individual netcdf files in a common directory (./cmip6). Similarly, the tlm/sterodynamics module uses pre-saved output for ocean heat content ("twolayer_SSPs.h5") and expansion coefficients ("scmpy2LM_RCMIP_CMIP6calpm_n18_expcoefs.nc"), that is (I think) also derived from a selection of CMIP6 models. See for example:
https://github.com/radical-collaboration/facts/blob/43bd25b564c963e8fa41f15178bd07fa02cdd583/modules/tlm/sterodynamics/Import2lmData.py#L55

From what I can see, there does not seem to be a way to subselect models. All available output is automatically loaded by the preprocessing script (`tlm_preprocess_oceandynamics.py`).

My questions are the following:
- Is it within the scope of FACTS to allow the user to subselect or add new climate models for ocean dynamic projections?
- If yes, how do we prepare the model data to be used as input for the sterodynamics module (such that it is compatible with the loading and processing within `tlm_preprocess_oceandynamics.py`)?
- Also, if we do use other models (or a subset of available ones in /cmip6), how will this impact the comparability to sea level projections from other modules that rely or are tuned from CMIP6 data (e.g., fair/temperature module)?

**Comment by bobkopp** [comment]
I think adding or subselecting new climate models for the zos/zostoga calibration could be within scope, but needs to be coded. Note that within tlm/sterodynamics, CMIP6 models are used only for calibrating the relationships between OHC and zostoga, and between zostoga and zos. This may require bringing some pre-processing of CMIP6 output that happened offline into FACTS. (See https://github.com/radical-collaboration/facts/issues/129) 

The pre-saved twolayer_SSPs.h5 is deprecated, and should not be used if you are running an up-to-date version of FACTS with an experiment configuration that looks like the typical examples. The version used in modern configurations should be generated by a fair/temperature run prior to calling the tlm/sterodynamics module. This is core to how the tlm/oceandynamics module is set up -- it is designed to generate output consistent with the 2-layer climate model emulator (thus the name). If we want an oceandynamics module that does not use ocean heat content projections from fair/temperature, we should design an additional module that achieves these aims. Additional modules with different goals/configurations are certainly within scope for FACTS.

**Comment by jetesdal** [comment]
Thank you @bobkopp for your response and the clarification. I have spent a bit more time dissecting the code to understand how we could implement the necessary code modifications to allow subselecting or adding new climate models.

You mentioned that loading pre-saved twolayer_SSPs.h5 file is deprecated, but the default still seems to be based on what I see in `tlm_preprocess_oceandynamics.py`:
https://github.com/radical-collaboration/facts/blob/43bd25b564c963e8fa41f15178bd07fa02cdd583/modules/tlm/sterodynamics/tlm_preprocess_oceandynamics.py#L355

Would it be possible to point me to the relevant code where the link between the generated ocean heat content projections from the `fair/temperature` output and the `tlm/sterodynamics` module is established? Specifically, I am interested in understanding how the `%CLIMATE_DATA_FILE%` "magic variable" is used to facilitate this connection, as I could not find any clear description of it in the documentation.

**Comment by bobkopp** [comment]
Yes, the default is retained in case a user wants to run the module in isolation, but the standard experiments provided, a climate step is run before the sea level step, and the climate output file is passed along to the modules run in the sea level components step. See FACTS.py for the code that translates the magic variables. You should have the climate output data file in the experiment output directory as well if you want to examine it.
________________________________

**Comment by bobkopp** [comment]
Merged into https://github.com/radical-collaboration/facts/issues/171
