### ISSUE TITLE
Consistency between `fair/temperature` and `tlm/sterodynamics` modules using the same set of CMIP models

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#169]
## Issue

I noticed that the `fair/temperature` and `tlm/sterodynamics` modules in FACTS rely on different sources of data for their calibration. The `fair/temperature` module uses pre-calibrated AR6 parameters ("./parameters/fair_ar6_climate_params_v4.0.nc") (see https://github.com/radical-collaboration/facts/blob/43bd25b564c963e8fa41f15178bd07fa02cdd583/modules/fair/temperature/fair_temperature_fit.py#L11), while the `tlm/sterodynamics` module uses a separate set of CMIP6 model output (see https://github.com/radical-collaboration/facts/blob/43bd25b564c963e8fa41f15178bd07fa02cdd583/modules/tlm/sterodynamics/tlm_preprocess_oceandynamics.py#L182). To ensure consistency in sea-level projections, it would be ideal to have both modules tuned to the same set of CMIP models. I was not able to determined if this is the case.

## Proposal
To ensure consistency and to allow for more flexibility in the set of CMIP model output (see #167 ), I propose the following steps:

1. **Obtain FaIR model parameters for a specific set of CMIP models**: Analyze the output from the chosen CMIP models, fit the parameters (climate sensitivity, effective radiative forcing, and heat uptake) to match the model behavior, and create a new parameter file for the FaIR model.

2. **Preprocess CMIP6 output for the `tlm/sterodynamics` module**: Obtain `zos` and `zostoga` data for the chosen CMIP models, apply drift correction, and calculate correlations. With this processed data, calibrate the relationships between ocean heat content, `zostoga`, and `zos` for the specific set of CMIP models.

3. **Modify FACTS configuration files**: Allow the configuration file in FACTS to use user-specified set of CMIP models for both the parameter inputs to the FaIR model and the preprocessing for the `tlm/sterodynamics` module.

By following these steps, we can ensure that both the `fair/temperature` and `tlm/sterodynamics` modules are tuned based on the same set of CMIP models, thereby maintaining consistency in sea-level projections.

## Question

Is this a viable approach? I would appreciate any feedback or corrections to the assessment presented above. If there are any existing tools or resources to assist with these tasks, please let me know.

**Comment by bobkopp** [comment]
The AR6 assessment used to calibrate FAIR is not based on the CMIP6 ensemble, so this would be a substitution of a different approach. It strikes me as a reasonable approach to try for experimental purposes, but it would be an inappropriate default. The goal of the current configuration is to produce probabilistic projections, which calibrating FAIR to individual CMIP6 modules would not do.
________________________________
From: Jan-Erik Tesdal ***@***.***>
Sent: Saturday, April 1, 2023 6:42:29 PM
To: radical-collaboration/facts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [radical-collaboration/facts] Consistency between `fair/temperature` and `tlm/sterodynamics` modules using the same set of CMIP models (Issue #169)


Issue

I noticed that the fair/temperature and tlm/sterodynamics modules in FACTS rely on different sources of data for their calibration. The fair/temperature module uses pre-calibrated AR6 parameters ("./parameters/fair_ar6_climate_params_v4.0.nc") (see https://github.com/radical-collaboration/facts/blob/43bd25b564c963e8fa41f15178bd07fa02cdd583/modules/fair/temperature/fair_temperature_fit.py#L11), while the tlm/sterodynamics module uses a separate set of CMIP6 model output (see https://github.com/radical-collaboration/facts/blob/43bd25b564c963e8fa41f15178bd07fa02cdd583/modules/tlm/sterodynamics/tlm_preprocess_oceandynamics.py#L182). To ensure consistency in sea-level projections, it would be ideal to have both modules tuned to the same set of CMIP models. I was not able to determined if this is the case.

Proposal

To ensure consistency and to allow for more flexibility in the set of CMIP model output (see #167<https://github.com/radical-collaboration/facts/issues/167> ), I propose the following steps:

  1.  Obtain FaIR model parameters for a specific set of CMIP models: Analyze the output from the chosen CMIP models, fit the parameters (climate sensitivity, effective radiative forcing, and heat uptake) to match the model behavior, and create a new parameter file for the FaIR model.

  2.  Preprocess CMIP6 output for the tlm/sterodynamics module: Obtain zos and zostoga data for the chosen CMIP models, apply drift correction, and calculate correlations. With this processed data, calibrate the relationships between ocean heat content, zostoga, and zos for the specific set of CMIP models.

  3.  Modify FACTS configuration files: Allow the configuration file in FACTS to use user-specified set of CMIP models for both the parameter inputs to the FaIR model and the preprocessing for the tlm/sterodynamics module.

By following these steps, we can ensure that both the fair/temperature and tlm/sterodynamics modules are tuned based on the same set of CMIP models, thereby maintaining consistency in sea-level projections.

Question

Is this a viable approach? I would appreciate any feedback or corrections to the assessment presented above. If there are any existing tools or resources to assist with these tasks, please let me know.

**Comment by bobkopp** [comment]
Further thoughts: what is the experimental goal here? If the objective is simply to match a CMIP6 simulation for a climate scenario run in CMIP6, there is no reason not to use CMIP6 output directly, and a new module to handle that would be the correct approach. The current framework is intended to: (1) work with any emissions scenario, regardless of whether run in CMIP6, and (2) ensure consistency with ECS and TCR as assessed based on multiple lines of evidence. Different goals require different modules.

**Comment by jetesdal** [comment]
Thanks @bobkopp for your response and input. The goal here is to enable running FACTS with a user-defined set of CMIP models across all different modules. This is related to Issue #167, which aims to allow users to subselect or add new climate models for ocean dynamic projections. The purpose of this issue is to address the potential inconsistency that may arise when using different sets of CMIP models for different modules within FACTS.

For example, if we produce ocean dynamic projections (using a new sterodynamics module) with a set of GFDL climate models, shouldn't the climate step be adjusted to reflect this? My thought is that we want temperature and heat content changes, which are then applied to the relevant modules (e.g., icesheet module), be consistent with the CMIP models that are used for the sterodynamics part.

**Comment by bobkopp** [comment]
Yes, I think the proposal would be to develop two new modules for directly using CMIP6 output, one which packages the CMIP6 TAS in a format usable by other modules, and one which turns CMIP6 zos and ZOSTOGA into a format that the totaling module can use. You may also want to replicate the results multiple times so that other modules are able to sample parametric uncertainty (since the numbers of FACTS samples equals the number of climate samples provided).
________________________________

**Comment by bobkopp** [comment]
Merge into https://github.com/radical-collaboration/facts/issues/171
