### ISSUE TITLE
Make `emulandice` set up easier on a generic system

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#177]
Per Reviewer 1:

> The code base includes a large number of dependencies, including heavy dependence on R. The authors provide some guidance in how to install the dependency, but it appears set up for their specific system, and not particularly user-friendly for the larger scientific community. In particular, library location and work directory are hard-coded in files disseminated throughout the project (in individual modules), as opposed to clearly indicated in a centralised configuration file. 
> For instance, to run the config provided in the doc:
> cp -r experiments/coupling.ssp585/config.yml test
> 
> python3 runFACTS.py test
> first fails because of missing files in modules/emulandice/shared (emulandice_1.1.0.tar.gz and emulandice_bundled_dependencies.tgz). To produce them, it was necessary to set up a local R environment. This required among other things to edit: 
> modules/emulandice/shared/emulandice_environment.sh : the line “module use /projects/community/modulefiles” had to be commented out.
> modules/emulandice/shared/emulandice_bundle_dependencies.R: 
> 
> packrat::set_opts(local.repos = c("/projects/community/R3.6_lib_workshop","."))
> 
> packrat::install_local('cli')
> 
> …
> Needed to be replaced with more traditional:
> install.packages('cli') 
> The authors did provide a README file in that directory with the mention:
> 
> “You will likely need to customize emulandice_environment.sh and emulandice_bundle_dependencies.R based on your local environment.”
> 
> But we recommend the default to be setup for generic linux system, and “customization” reserved for use on the authors HPC, instead of (currently) the opposite.
>

**Comment by bobkopp** [comment]
In the branch, I've made nicer defaults. 

Ideally, invoking the commands specified in the README should be done by a module package management system, but that does not currently exist. I suggest creating a single shell script for the purpose that creates the emulandice and dependencies tar files *if they don't already exist*. Ideally, we would implement functionality in the FACTS Manager to invoke this script when an emulandice module, before the module is dispatched to the compute resource, doing nothing if the files already exist and creating them if they do.

**Comment by AlexReedy** [comment]
I am currently working on a basic install.sh that handles this (along with the rest of the basic installation stuff), you want emulandice to handled in it's own sh?

**Comment by bobkopp** [comment]
Yes, we want to evolve to a point where each module has its own install script (i.e., there is a package management system). Your install.sh can call this module-level script.

I have created such as script (``emulandice_config.sh``) in the branch.

Note that the install script for setting up a virtual machine (previously called ``mac_docker_factsenvsetup.sh``, now called `vm_factsenvsetup.sh`` in the branch) may do much of what you want from a basic install script, as it is designed to go from a vanilla Ubuntu VM to a running environment.
