### ISSUE TITLE
Run FACTS on Perlmutter

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/facts#179]
@matthewhoffman would like to run FACTS on Perlmutter. The RADICAL team should preemptively verify the status of EnTK/RP support of Perlmutter. Further support might be needed to support Matt for his testing phase.

**Comment by mturilli** [comment]
Hi @matthewhoffman , in order to help you to run FACTS on Perlmutter, we are planning the following:
- Run some tests ourselves on Perlmutter to confirm that we still support it without issues.
- Verify that we can give you an account on our MongoDB server so that you can test FACTS right away without having to wait for NERSC to provide a dedicated instance for you.

I added the above to our (RADICAL team) development sprint, we should be able to get back to you at the beginning of next week.

**Comment by matthewhoffman** [comment]
@mturilli , that all sounds great, thank you!  Let me know if/when I can test anything out.

**Comment by mturilli** [comment]
Hi @matthewhoffman , it turned out that we needed to create a new configuration file. That requires some more testing that we expected. We have access to the machine and we are getting ready to run some test. As a side note, they provided us with a mongodb so also that part of the ticket has been progressing. We will ping back once we have the results of the tests.

**Comment by matthewhoffman** [comment]
@mturilli , thanks for the update.  Thanks for the additional work on this.

**Comment by mturilli** [comment]
Hi @matthewhoffman , an update to let you know that we now support Perlmutter and our initial tests were successful. We requested and used a MongoDB instance provided by NERSC so you will be able to use the same service.

@AlexReedy , I think the next step is to discuss about how to run FACTS on Perlmutter and do the preliminary tests. As a starting point, please see https://radicalpilot.readthedocs.io/en/devel/supported/perlmutter.html . Once you are ready, we will be happy to discuss and test FACTS together.

**Comment by mtitov** [comment]
NOTE: for now Perlmutter setup and configuration is available in the devel-branch (not released yet), it is for both RADICAL-Pilot and RADICAL-SAGA
```
pip install git+https://github.com/radical-cybertools/radical.saga.git@devel
pip install git+https://github.com/radical-cybertools/radical.pilot.git@devel
```

**Comment by matthewhoffman** [comment]
@mturilli & @mtitov , thanks for the updates.  Should I go ahead and try things out now, (once Perlmutter's current issues are resolved) or wait until you and @AlexReedy have done further testing?

**Comment by AlexReedy** [comment]
Hey everyone, I believe we have a setup meeting on Wednesday correct? Is this at the same time as the sprint sync?

**Comment by matthewhoffman** [comment]
@AlexReedy , thanks for the update, and sorry for the slow reply.  

It had sounded to me from @mturilli 's comments that the FACTS/Radical team already has access to Perlmutter.  If that's not the case, I can instead add you to our allocation.  Follow up with me by email, and I can direct you for how to get that established.

**Comment by shantenujha** [comment]
Hi @matthewhoffman Some of the RADICAL team is based at Brookhaven and involved with DOE projects, which is how some of us have access to Perlmutter. @AlexReedy as of now doesn't, thus his lack of access. It would indeed be quickest if you were able to add him to your project/allocation, as bringing him onto Perlumutter via DOE projects would take time.  Let us know, please.

**Comment by AlexReedy** [comment]
Thanks Matthew, will start the process today

**Comment by AlexReedy** [comment]
ok account has been created and just waiting for the vetting process to conclude @matthewhoffman said it should be a couple of days

**Comment by mturilli** [comment]
Hi @AlexReedy , any news on testing FACTS on Perlmutter?

**Comment by AlexReedy** [comment]
Hey sorry meant to post an update yesterday but got taken away. Mentioned to @matthewhoffman last week that I wouldn't be working on this until mid-this week.  If anyone is available to meet and walk me through the actual getting onto Perlmutter I would much appreciate that

**Comment by matthewhoffman** [comment]
@AlexReedy , the place to start is the NERSC documentation here: https://docs.nersc.gov/getting-started/ but I'm happy to talk through specific questions you might have after reading that, probably on Slack.  Note that Perlmutter is down for maintenance today but login nodes should be up later today.

**Comment by AlexReedy** [comment]
@matthewhoffman got access to Perlmutter today and have facts mostly installed, trouble shooting some mongodb stuff currently but wanted to update you regardless. After I have succesfully run the dummy experiment I will look into how to get the data files onto perlmutter

**Comment by AlexReedy** [comment]
Hey all @mtitov and I did some work on setting up mongodb to work and managed to have a successful dummy experiment run on perlmutter using the 'debug' queue. When we tried to run on regular we ran into an issue with the walltime having an apparent violation of  qos/accounting policy which we're investigating as our submitted time was well below the queues upper limit. I'm sending the info to the NERSC support team to see what they have to say.

**Comment by AlexReedy** [comment]
Got a reply from NERSC support telling us we need to add in another flag to the batch script for assigning the qos to regular as right now it defaults to debug which has a 30min time limit. @mtitov is working on the fix!

**Comment by AlexReedy** [comment]
@mtitov sent over a fix and it seems to be working now!

**Comment by mturilli** [comment]
@AlexReedy , well done! @matthewhoffman , I think that we are now ready for you to test FACTS on Perlmutter. Alex should be able to help you with that if needed. Once you confirm that the test was successful I will close the ticket. Thank you for your patience!

**Comment by AlexReedy** [comment]
Thanks @mturilli, and yes Matthew if you need help please let me know!

**Comment by AlexReedy** [comment]
Hey @matthewhoffman are we ok to close this out? Or was there anything further you wanted to discuss?

**Comment by matthewhoffman** [comment]
Hi @AlexReedy , thanks for following up. Yes, we can close this now.  I will be having a new team member joining my project next month, at which point I'll be working on this more actively.

**Comment by AlexReedy** [comment]
Ok excellent, please feel free to send me an email once your student comes in and you guys start working more with FACTS
