### ISSUE TITLE
Create docker container

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#180]
The use of `scripts/vm_factsenvsetup.sh` demonstrates the feasibility of this, but a proper Dockerfile needs to be created, ideally composed in a way that doesn't require 5-10 minutes of setup each time the container is run.

**Comment by AlexReedy** [comment]
I do have a Docker image saved, but would love to talk to @andre-merzky and @mturilli about if the way I have it set up is the best way to do it.
