### ISSUE TITLE
totaling scripts is inefficient in use of memory

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#184]
``facts/total`` has a tendency to run out of memory when running with many thousand samples and thousands of locations. The IPCC AR6  projections got around this by running the totaling script on a high-memory with 1 TB of memory (https://github.com/radical-collaboration/facts/blob/ipccar6/scripts/total_workflows.sh), but this is not an optimal solution.

**Comment by bobkopp** [comment]
The problem might also be here:

`		# Open this component file
		with xr.open_dataset(infile, chunks={"locations":chunksize}) as nc:

			# If this is the first successfully loaded file, initialize the total,
			# otherwise, add to the total
			if first_file:
				total_sl = nc["sea_level_change"].sel(years=targyears)
				site_lats = nc["lat"]
				site_lons = nc["lon"]
				site_ids = nc["locations"]
				sample_val = nc["samples"]
				first_file = False
			else:
				total_sl += nc["sea_level_change"].sel(years=targyears)
`

where all the variables are pulled out of the xarray Dataset into something not handled by xarray.

**Comment by bobkopp** [comment]
Brewster makes the following suggestion based on `open_mfdataset`:

```
def TotalSamples(infiles, outfile, targyears, chunksize):
	# Skip this file if it appears to be a total file already
	# SBM: FWIW, this might not work as intended because path is appended to file names in funcs above.
	target_infiles = [fl for fl in infiles if not re.search(r"^total", fl)]

    # Reads in multiple files (delayed) and tries combine along
    # common dimensions and a new "file" dimension.
	ds = xr.open_mfdataset(
		target_infiles, 
	    combine="nested", 
	    concat_dim="file", 
	    chunks={"locations":chunksize},
	)
	ds = ds.sel(years=targyears)
	# Sums everything across the new "file" dimension.
	total_out = ds[["sea_level_change"]].sum(dim="file")

	# Attributes for the total file
	total_out.attrs = {
		"description": "Total sea-level change for workflow",
		"history": "Created " + time.ctime(time.time()),
		"source": "FACTS: Post-processed total among available contributors: {}".format(",".join(infiles)),
	}

	# Define the missing value for the netCDF files
	nc_missing_value = np.iinfo(np.int16).min
	total_out["sea_level_change"].attrs = {
		"units": "mm", 
		"missing_value": nc_missing_value
	}

	# Write the total to an output file.
    # This actually carries out the delayed calculations and operations.
    # SBM: FYI Double check the numbers to ensure everything is summing across dims correctly.
    # SBM: FYI Also, check to see if output as something huge like float64.
	total_out.to_netcdf(outfile, encoding={"sea_level_change": {"dtype": "i2", "zlib": True, "complevel":4, "_FillValue": nc_missing_value}})

	return(outfile)
```

**Comment by AlexReedy** [comment]
ok once this run concludes (it's still going) I will implement and test

**Comment by AlexReedy** [comment]
Implemented this this morning and am about an hour into the test run. What is the best way to determine if the outputs are correct?

**Comment by bobkopp** [comment]
Outputs from the two version should be numerically identical and file size should be comparable.
