### ISSUE TITLE
Default experiments do not extrapolate ice sheet rates after 2100

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#193]
This is a difference from the AR6 implementation that should be noted and correctly described. Also note that larmip/AIS, unlike ipccar6/larmipAIS, does not currently have the ExtrapolateRate function implemented.

**Comment by bobkopp** [comment]
The `ExtrapolateRate` function from `ipccar6/larmipAIS/ipccar6_larmipicesheet_project.py` should be implemented in `larmip/AIS/larmip_icesheet_project.py`. The different components should then be extrapolated before being written, e.g.:

```

	if cyear_start or cyear_end:
		for i in np.arange(nsamps):
			sl_r1[i,:] = ExtrapolateRate(sl_r1[i,:], years, cyear_start, cyear_end)
			sl_r2[i,:] = ExtrapolateRate(sl_r1[i,:], years, cyear_start, cyear_end)
			sl_r3[i,:] = ExtrapolateRate(sl_r1[i,:], years, cyear_start, cyear_end)
			sl_r4[i,:] = ExtrapolateRate(sl_r1[i,:], years, cyear_start, cyear_end)
			sl_r5[i,:] = ExtrapolateRate(sl_r1[i,:], years, cyear_start, cyear_end)
			sl_smb[i,:] = ExtrapolateRate(sl_r1[i,:], years, cyear_start, cyear_end)

	# Combine all Antarctic regions into Antarctica projection
	sl_su = sl_r1 + sl_r2 + sl_r3 + sl_r4 + sl_r5

	# Sum up the WAIS components
	wais_samples = sl_r2 + sl_r3 + sl_r4

 
```

The results should then be compared when run with `cyear_start` = 2080 and `cyear_end` = 2100 to confirm alignment with the AR6 results.

**Comment by AlexReedy** [comment]
We are testing a first pass fix of this today

**Comment by pkjr002** [comment]
Updated modules of `Larmip/AIS` and `ipccar6/larmipAIS` for allowing extrapolation. Plotted result, see attached pdf. Let me know if something looks amiss. 

[endofcent_.pdf](https://github.com/radical-collaboration/facts/files/12470898/endofcent_.pdf)

**Comment by bobkopp** [comment]
Looks good to me.

**Comment by bobkopp** [comment]
Was this addressed successfully by https://github.com/radical-collaboration/facts/pull/212 ?

**Comment by pkjr002** [comment]
Yes #212 addressed this successfully; this issue can be closed.
