### ISSUE TITLE
Amarel no longer recognizes virtual environment through RCT

### ISSUE THREAD

**Issue by AlexReedy** [radical-collaboration/facts#215]
After the 09/19/2023 update, Amarel no longer recognizes the activation of user generated virtual environments when running through RCT.

**Comment by bobkopp** [comment]
Was this successfully resolved?

**Comment by AlexReedy** [comment]
Yes this is resolved through a hotfix

**Comment by AlexReedy** [comment]
Resolved with hotfix to pre_exec
