### ISSUE TITLE
EnTK Documentation/Questions

### ISSUE THREAD

**Issue by ggg121** [radical-collaboration/facts#23]
In developing the "totaling" and "extreme sea-level" portions of the framework, I've come up with a list of questions about EnTK and how it works.  Below are the questions:

1. In section 6.1 in the EnTK documentation, the use of a stage's "post_exec" method is ambiguous. The documentation here and in the Stage API (section 7.1.2) indicate the use of a dictionary whereas the example illustrates the use of a function.  Which is the appropriate usage?
2. Does a shared directory for the EnTK session exist that I can have individual tasks write to, even if it's not setup within the application manager?
3. The description of the "copy_output_data" in the Task API (7.1.3) is ambiguous. This method should copy task output files to a new location on the remote machine within the same EnTK session.  I would expect this to require information about both the file to copy and where to copy it.  The syntax for "download_output_data" looks closer to what I would expect for this method.  What's the proper syntax for the "copy_output_data" usage?  Perhaps an example would be useful?

**Comment by karahbit** [comment]
I will attempt to give my answers to the above questions:

1. According to [post_exec.setter](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/stage/stage.py#L183), it takes as a value any object that can be called, i.e., functions or methods. Then, you would have to follow the logical structure for the post_exec in the execution of the functions:
```
    s.post_exec = {
                'condition': name of boolean function,
                'on_true': function to be executed if boolean result is True,
                'on_false': function to be executed if boolean result is False
            }
```

2. It does exist, and you can reference it as the variable `$SHARED`, which is only accessible inside the scope of the EnTK session. You can see an example of the usage [here](https://github.com/radical-cybertools/radical.entk/blob/devel/examples/user_guide/add_shared_data.py#L68)

3. This function copies files from the location of the current task to another location on the remote machine. It takes as an argument a list of strings. So, as we see in this [example](https://github.com/radical-cybertools/radical.entk/blob/devel/examples/user_guide/add_data.py#L49) for `copy_input_data`, all we need to specify is the location where we want to copy the files to, like this:
```
    t1.copy_output_data = ['$Pipeline_%s_Stage_%s_Task_%s/file.txt'%(p.uid, s2.uid, t2.uid)]
```

**Comment by lee212** [comment]
Hi @ggg121 ,

I am updating EnTK documentation to address `post_exec` and `copy_output_data`. You correctly spotted the inconsistency of the documentation as we use automation to generate API documentation from source code, I have to execute there can be dated description.  These are currently under entk `fix/docs` branch, and I will merge soon.
