### ISSUE TITLE
Extend bamber19 interpolation scheme to deconto21

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#238]
Based on CCSM temperature projections used in the paper, integrated 21st century temperature is about 133, 167 and 245 C*yr for RCP 2.6, 4.5 and 8.5, respectively.

Taking an approach similar to that newly implemented for bamber19, can use a weighted mixture of the rcp2.6 and rcp4.5 distributions for projections between 133-167, and of the rcp4.5 and rcp8.5 distributions for 167-245.

**Comment by bobkopp** [comment]
Prototyped this in the `deconto21/interp` branch but have not done any validation, or indeed confirmed code runs.

**Comment by AlexReedy** [comment]
Validated functionality closing issue
![deconto21_AIS_AIS_unmodified__2100](https://github.com/radical-collaboration/facts/assets/68187517/721272f4-9c16-4a43-8800-bb50027a76bc)
![deconto21_AIS_AIS_modified__2100](https://github.com/radical-collaboration/facts/assets/68187517/30aa4fc1-de99-45d2-8f80-12492beaacad)
![deconto21_AIS_EAIS_unmodified__2100](https://github.com/radical-collaboration/facts/assets/68187517/1fc46f5f-a5ac-499d-b163-e79d760e4a2e)
![deconto21_AIS_EAIS_modified__2100](https://github.com/radical-collaboration/facts/assets/68187517/712c7e9b-321b-4996-ae04-b886736bf4d6)
![deconto21_AIS_WAIS_unmodified__2100](https://github.com/radical-collaboration/facts/assets/68187517/5992366f-51ba-436e-b604-a5d724bb0ae0)
![deconto21_AIS_WAIS_modified__2100](https://github.com/radical-collaboration/facts/assets/68187517/921ce02c-8475-42d8-93c8-bf742fedd6e8)
