### ISSUE TITLE
EnTK App Manager hangs when processing second workflow

### ISSUE THREAD

**Issue by ggg121** [radical-collaboration/facts#24]
I submit a list of pipelines (SLR contributors) to the app manager and run the app manager.

```
# Initialize the EnTK App Manager
amgr = AppManager(hostname=rcfg['rabbitmq']['hostname'], port=rcfg['rabbitmq']['port'])
	
# Apply the resource configuration provided by the user
res_desc = {'resource': rcfg['resource-desc']['name'],
	'walltime': rcfg['resource-desc']['walltime'],
	'cpus': rcfg['resource-desc']['cpus'],
	'queue': rcfg['resource-desc']['queue'],
	'project': rcfg['resource-desc']['project']}
amgr.resource_desc = res_desc
	
# Assign the list of pipelines to the workflow
amgr.workflow = pipelines
		
# Run the workflow
amgr.run()
```

This executes correctly (`pipelines` and `rcfg` have already been defined).  I then assign a new list of pipelines to the same app manager and attempt to run the workflow. 

```
# New pipeline
p1 = Pipeline()
p1.name = "Test-pipeline"
	
# First stage with one task
s1 = Stage()
s1.name = "Test-stage"
t1 = Task()
t1.name = "Test-task"
t1.executable = '/bin/sleep'
t1.arguments = ['1']
	
# Second stage with one task
s2 = Stage()
s2.name = "Test-stage2"
t2 = Task()
t2.name = "Test-task2"
t2.executable = '/bin/sleep'
t2.arguments = ['5']
	
# Assign tasks and stages to pipeline
s1.add_tasks(t1)
s2.add_tasks(t2)
p1.add_stages(s1)
p1.add_stages(s2)
	
# Assign the pipeline to the workflow and run
amgr.workflow = [p1]
amgr.run()
```

The workflow hangs, seemingly indefinitely, after submitting the first task/stage/pipeline.  I need to send a KeyboardInterrupt to stop execution.  The error seems to be related to checking for a heartbeat.

```
Traceback (most recent call last):
  File "/home/ggg46/slr_venv3/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 195, in _tmgr
    raise EnTKError(e)
radical.entk.exceptions.EnTKError: (404, "NOT_FOUND - no queue 're.session.ggg46-vb.ggg46.018393.0004-hb-request' in vhost '/'")
```

Am I doing something wrong, or is this a potential bug in EnTK?  Attached are the log files from this session.
[verbose.log](https://github.com/radical-collaboration/facts/files/4611999/verbose.log)
[re_logs.zip](https://github.com/radical-collaboration/facts/files/4612023/re_logs.zip)

**Comment by ggg121** [comment]
Here's the output of `radical-stack`:

```
(slr_venv3) ggg46@ggg46-vb:~$ radical-stack

  python               : 3.7.5
  pythonpath           : /home/ggg46/pylibs/ssht
  virtualenv           : /home/ggg46/slr_venv3

  radical.entk         : 1.0.2
  radical.pilot        : 1.2.1
  radical.saga         : 1.2.0
  radical.utils        : 1.2.2
```

**Comment by ggg121** [comment]
I've created a "devel" branch to help with this issue.

**Comment by lee212** [comment]
Hi @ggg121 ,

I think I can suggest one quick solution for your second pipeline. you may want to create new `appman` for the start. `appmnan.run()` contains implicitly termination e.g. termination of heartbeat to listen, and your `appman` just needs a new instance start your second pipeline. For example,

```
appman1 = AppManager()
...
appman1.run()
### pipeline 1 finished
appman2 = AppManager()
...
appman2.run()
### pipelin 2 runs on a new appmanager instance
```

**Comment by ggg121** [comment]
Hi @lee212 ,

Starting up a second application manager should let me start the second workflow, but an additional constraint to this problem is that the second workflow relies on access to data produced and organized in the first workflow.  Using a second application manager would mean downloading all the intermediate output from remote to local just to have to upload it again back to the remote and reorganize, which seems inefficient.

Thank you for your time and effort on this.  Unfortunately, a second application manager isn't a great option at the moment...but if it's the only way forward, then I'll need to rethink my approach.

**Comment by lee212** [comment]
FYI, @andre-merzky provided a solution with the example here: https://gist.github.com/andre-merzky/e74f807fdf8eb43f3a9feb158745d934

It suggests starting `AppManager` with `autoterminate=False`  and using `appman.terminate()` once all pipelines are finished. This allows you to use the same application manager for the second workflow.

**Comment by ggg121** [comment]
I gave the proposed solution a try with the very simple second workflow I described above.  The solution seems to be working well.  I have one last aspect I would like to test before I can confirm this solution works for my application, but I'm fairly optimistic.

**Comment by ggg121** [comment]
It looks as though my subsequent workflows have access to the data and file organization produced from the prior workflows.  This was vital for my application, so at this point I'm comfortable saying this solution works.  Thank you @andre-merzky and @lee212 for your help on this.
