### ISSUE TITLE
Needs clearer documentation of how to set up new resources

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#246]
Right now, it is straightforward to run on localhost, but there are no clear instructions on how to run on a new system. Please provide clearer guidance in the docs. At a minimum, please provide instructions to submit a ticket on the EnTK repo (or whatever appropriate)

**Comment by AlexReedy** [comment]
So this would be for users to understand:
1. To reach out to RCT about setting up on their HPC
2.  Once the setup is complete how to create their resource.yml file to run
@andre-merzky I believe most of this information is contained in the RCT tutorials right?

**Comment by bobkopp** [comment]
Presumably this is all in the RCT tutorials, but FACTS users need to be directed to the parts they need to know and should not be expected to seek out the RCT tutorials on their own.

**Comment by AlexReedy** [comment]
Oh I agree, just synthesizing info for our documentation

**Comment by bobkopp** [comment]
Added text -- If you need to run on a HPC resource not previously configured for RADICAL-Pilot, the resource will need to be configured. To get assistance with this, create an issue on the RADICAL-Pilot repo.
