### ISSUE TITLE
Allow more precision in output

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#268]
The netcdf files outputted by the sea-level component modules and total modules use 16-bit (i2) integers for sea level in mm. Thus, sub-mm differences are not preserved. This may lead to some of the erratic rounding differences between runs we occasionally see, and also causes problems for experiments intended to look at small changes due to pulse emissions. We should see whether converting the `dtype` for `sea_level_change` variables from `i2` to `f4` breaks anything, or yields inconsistencies with results reported in the GMD paper. If not, we could adopt this as a new default, but future versions should allow this data type to be set as a parameter, as this will lead to a doubling of file size.

**Comment by bobkopp** [comment]
This branch as I initially pushed it **will not work** because, at a minimum, of the way netcdf4 missing_value/_FillValue is handled. This is currently set in most modules to
```
nc_missing_value = np.iinfo(np.int16).min
```
which only makes sense if the variable being stored is `i2`. 

Before making this change, someone needs to go through the logic of the netcdf4 missing values. @AlexReedy @JMGilbert maybe you two could confer on this?

**Comment by bobkopp** [comment]
From https://docs.xarray.dev/en/stable/user-guide/io.html:

```
_FillValue: Values of NaN in xarray variables are remapped to this value when saved on disk. This is important when converting floating point with missing values to integers on disk, because NaN is not a valid value for integer dtypes. By default, variables with float types are attributed a _FillValue of NaN in the output file, unless explicitly disabled with an encoding {'_FillValue': None}.
```

We seem to use both `_FillValue` and `missing_value` in different places. I am unclear on the difference between the two but suspect this difference is not used deliberately (see https://github.com/pydata/xarray/issues/17490). It is possible that all references to either _FillValue or missing_value can be eliminated, and or a simple global replace to:

```
nc_missing_value = np.NaN
```
will work. This seems like it would be consistent with https://www.unidata.ucar.edu/software/netcdf/workshops/2011/bestpractices/MissingData.html

**Comment by AlexReedy** [comment]
Just ran a successful run of coupling.ssp585 (without emulandice) with the changes made at nsamps=200. Running again now at 2000 samples to do the quantile comparisons for the other modules.
