### ISSUE TITLE
Document Data Use / Storage Information

### ISSUE THREAD

**Issue by AlexReedy** [radical-collaboration/facts#277]
Current FACTS requires a fairly sizable amount of RAM and each experiments outputs ~30GB+ of data to disk.  While an automatic cleanup method will be useful in the future for now we should note this within the documentation.

**Comment by bobkopp** [comment]
For use cases where users only want global data, https://github.com/radical-collaboration/facts/issues/278 should also help.

**Comment by bobkopp** [comment]
https://github.com/ClimateImpactLab/dscim-facts-epa states that:

> Running FACTS is a relatively memory-intensive and disk-space-intensive process. To successfully run FACTS, you will need a moderately powerful workstation (or server) with at least 32 gigabytes of computer RAM. By default, FACTS uses two CPU cores and is not particularly sensitive to clock speed or number of CPU cores. In addition, FACTS currently requires around 30 gigabytes of disk space per pulse year-gas, which means that 3 gases and 7 pulse years (a total of 22 runs including the control) will require approximately 660 gigabytes of disk space. Alternatively, one can run subsets of runs at a time and clear memory in between. To clear memory after a run has been completed, remove the subdirectories in the ~/radical.pilot.sandbox folder.

While the specific memory and disk requirements are dependent upon the experiment, so I would avoid a blanket statement about the sort here, it is worth flagging the accumulation of cruft in the sandbox.

**Comment by bobkopp** [comment]
Added notes to global_only branch.
