### ISSUE TITLE
Add pipelines to run tlm/sterodynamics and other modules for GMSL only

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#278]
tlm_sterodynamics_cmip6_data.tgz is very large and is not used in thermal expansion-only calculations, so we should have a bypass.

Proposed approach:

1. in tlm_sterodynamics_preprocess.py and tlm_sterodynamics_fit.py, add a '--te_only' options that skips the calls to `tlm_preprocess_oceandynamics` and `tlm_fit_oceandynamics`
2. create a pipeline.TEonly.yml that (a) sets the te_only option, (b) does not upload tlm_sterodynamics_cmip6_data.tgz, and (c) skips the postprocess stage

This bypass can then be invokved by adding `pipeline_file: "pipeline.TEonly.yml"` to the tlm_sterodynamics block in the experiment config.yml

**Comment by bobkopp** [comment]
Actually, maybe this should be generalized with a standard global_only option and pipeline.global_only.yml files.

**Comment by bobkopp** [comment]
We could also add a default-pipeline variable to global-options such that pipeline.global.yml could be set as the standard within a config without having to set it for every module individually. 

Note that there would also need to be a pipeline.AIS.global.yml for ipccar5/icesheets, since the standard runs use pipeline.AIS.yml rather than pipeline.yml.

**Comment by AlexReedy** [comment]
We have a working version of this for tlm and other modules. There does seem to be some hanging behaviour in emulandice now but it is uncertain if that is a result of a global / local pipeline. This is being tested now
