### ISSUE TITLE
Error using `emulandice_config.sh` script during installation

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#291]
I want to test the latest version of FACTS but I am encountering an issue while running the emulandice_config.sh script as described in the [Quick Start](https://fact-sealevel.readthedocs.io/en/latest/quickstart.html) page:
```
modules/emulandice/emulandice_config.sh
```
 The script fails during the execution, particularly when trying to build `emulandice_bundled_dependencies.tgz`.
 
 The script execution aborts with the following errors:
 ```
Currently Loaded Modules:
  1) gcc/11.2/openmpi/4.1.3-kholodvl   2) pcre2/10.35-gc563   3) R/4.1.0-gc563   4) cmake/3.24.3-sw1088


Building emulandice_1.1.0.tar.gz...
* checking for file ‘emulandice/DESCRIPTION’ ... OK
* preparing ‘emulandice’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘emulandice_1.1.0.tar.gz’
Warning in sprintf(gettext(fmt, domain = domain), ...) :
  one argument not used by format 'invalid uid value replaced by that for user 'nobody''
Warning: invalid uid value replaced by that for user 'nobody'
Warning in sprintf(gettext(fmt, domain = domain), ...) :
  one argument not used by format 'invalid gid value replaced by that for user 'nobody''
Warning: invalid gid value replaced by that for user 'nobody'

Building emulandice_bundled_dependencies.tgz...
Warning in install.packages("packrat") :
  'lib = "/projectsp/community/R/4.1.0/gc563/lib64/R/library"' is not writable
Error in install.packages("packrat") : unable to install packages
Execution halted
tar: .Rprofile: Cannot stat: No such file or directory
tar: packrat: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

In a previous version of FACTS (prior to #178) I was able to fix this by commenting out the installation of R packages `grDevices`, `grid`, `mgcv` and `stats` in `emulandice_bundle_dependencies.R`, since they are part of the core `R` distributiuon and caused the installation script to error out. However, this "hack" does not work with the updated "one-script-for-all" setup. Might this issue be related to permissions? Note that I am trying to do this on the Amarel cluster.

**Comment by bobkopp** [comment]
I was not able to replicate your error, but did need to switch in `emulandice_environment.sh` to the gcc module `gcc/10.2.0/openmpi`, a change that I have now made in both main and global_only, in order to get the R modules to build. I am not sure why packages would be trying to install to the global directory rather than to your home directory -- this is not the behavior I am seeing.

**Comment by bobkopp** [comment]
I would not advise using an old fork, FACTS 1.1 has substantial changes relative to FACTS 1.0 and I would not want to vouch for anything that happens if you are using an old version.

**Comment by bobkopp** [comment]
Broadly, Amarel+emulandice is being flaky right now, in response to system changes it appears, and @AlexReedy is looking for a way of setting up the environment on Amarel that depends less on the system state. In the mean time, I would advise not running emulandice in experiments on Amarel.

**Comment by bobkopp** [comment]
@jetesdal we are working to debug emulandice on Amarel and expect to have a fix in release 1.1.2.

**Comment by jetesdal** [comment]
Thank you for the updates and insights, @bobkopp. I'll keep an eye out for the next release. In the meantime, I'll try out the method described in [Quick Start 1.2](https://fact-sealevel.readthedocs.io/en/latest/quickstart.html#installing-and-using-facts-on-a-gnu-linux-container) and see if I can get a working FACTS using the container option on my Mac.

**Comment by bobkopp** [comment]
@jetesdal This issue should be addressed in the emulandice/packrat branch if you want to test it before the release. Make sure you are using Python 3.8.10 or higher before creating your virtual environment (on Amarel there is a community module for Python 3.9.6); there are some hard to trace issues that seem to be associated with earlier Python versions.

**Comment by AlexReedy** [comment]
@jetesdal I want to add to @bobkopp  comment, it does seem that emulandice safely works from 3.9.6 on, emulandice was not running on python 3.8.12 on my machine.
