### ISSUE TITLE
Write notebook that generates key figures and tables in FACTS 1.1.1 white paper

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#296]
This would provide an easy way to run tests based on output. Consider using numba or dask to parallelize submission of runFACTS for multiple emissions scenarios.

**Comment by bobkopp** [comment]
@AlexReedy Checking on the staus of this. Thanks!

**Comment by AlexReedy** [comment]
@bobkopp ok, finished with the datatables and am now doing a full run to verify
