### ISSUE TITLE
Support for Amarel

### ISSUE THREAD

**Issue by vivek-bala** [radical-collaboration/facts#3]
https://github.com/radical-cybertools/radical.pilot/issues/1813

**Comment by mturilli** [comment]
Both @mturilli and @andre-merzky need to be added to Kopp's allocation on Amarel. Will inquire on what is the process for doing that.

**Comment by ggg121** [comment]
@mturilli , I'll email Bob to get you two added to his condo on Amarel.

**Comment by ggg121** [comment]
@Abdullah-Ghani has been working on support for Amarel.  He's provided a resource configuration that seems to work well for FACTS workflows.  If there are no objections, I'll consider this issue solved.

**Comment by ggg121** [comment]
There seems to be no objections.  I'm considering this issue closed.
