### ISSUE TITLE
Download OceanDyn.nc in the tlm/sterodynamics pipeline so number of GCMs per grid cell can be used to define a land mask

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#310]
Right now we don't provide direct guidance to users on how to do a land mask. Probably the best approach is to look at number of GCMs contributing to DSL projections at each grid cell and help users use this to define a cutoff.

**Comment by jetesdal** [comment]
@bobkopp / @AlexReedy I am trying to find `OceanDyn.nc` and `OceanDynTECorr.nc` after running `tlm` with the latest facts. Is this currently still in development or should this be part of the main branch?
