### ISSUE TITLE
Make Output Directory a configuration parameter

### ISSUE THREAD

**Issue by AlexReedy** [radical-collaboration/facts#312]
Currently the output directory is hardcoded in runFACTS.py. We want to allow this directory to specified by the user per run if they want the experiment outputs to be placed outside of the experiment directory. If the out dire is not specified in the config then it should be defaulted to the exp directory as it currently is.

**Comment by bobkopp** [comment]
Correction: it is hard coded in both runFACTS and FACTS.
________________________________
From: AHReedy ***@***.***>
Sent: Friday, January 12, 2024 2:40:08 PM
To: radical-collaboration/facts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [radical-collaboration/facts] Make Output Directory a configuration parameter (Issue #312)


Currently the output directory is hardcoded in runFACTS.py. We want to allow this directory to specified by the user per run if they want the experiment outputs to be placed outside of the experiment directory. If the out dire is not specified in the config then it should be defaulted to the exp directory as it currently is.
