### ISSUE TITLE
Allow LWS module to infer socioeconomic scenario from global scenario label

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#319]
Because LWS needs socioeconomic scenarios (ssp1, ssp2, etc) rather than climate scenarios (ssp126, ssp245, etc), it currently needs its own scenario label in the config file. Add capability to infer corresponding socioeconomic scenario from global scenario label (eg use ssp1 if ssp119 or ssp126 is specified globally).

**Comment by AlexReedy** [comment]
Just did some test runs and it's looking like it's working but am going to run all SSPs and run through the notebook to make sure
