### ISSUE TITLE
Update EnTK and fix namespace for compatibility

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#32]
EnTK needs to be updated and module namespace adjusted so that FACTS.py runs properly.

**Comment by shantenujha** [comment]
@mturilli Please update on the status/progress, or reassign as needed. Thanks.

**Comment by bobkopp** [comment]
I've accepted this pull request. We still need to actually get the EnTK framework for FACTS working again, at which point we can see whether the change in naming convention broke anything.

**Comment by bobkopp** [comment]
If I understood what the hyphenation issue was, it was the presence of hyphens in the 'pre-process' and 'post-process' stage names. I've removed these. We will have to wait until we can run FACTS.py proper to see if it created problems.
