### ISSUE TITLE
Source / derivation for `expcoefs` and GSAT `rmses` in `tlm_sterodynamics_preprocess_thermalexpansion.py`

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#329]
I am trying to understand how to derive the variables in `scmpy2LM_RCMIP_CMIP6calpm_n18_expcoefs.nc` and `scmpy2LM_RCMIP_CMIP6calpm_n17_gsat_rmse.nc`. 
https://github.com/radical-collaboration/facts/blob/3ff08f91a8d8180b7058f8bcad884f0dc46dce53/modules/tlm/sterodynamics/tlm_sterodynamics_preprocess_thermalexpansion.py#L37-L47

**expcoefs**:
Expansion coefficients derived by regressing scmpy 2-layer model OHC against linearly dedrifted GTE for CMIP6 models, using CMIP6 calibration parameters with ERF from RCMIP

**gsat_rmse**:
RMSE of scmpy 2-layer model mixed layer temperature against GSAT for CMIP6 models obtained from Matt Palmer & Chris Jones across ssp126, ssp245 and ssp585 combined, using CMIP6 calibration parameters with ERF from RCMIP

Are these used in the current setup or is this a relict from the "offline approach"? Is there an official source/reference for this data? How should we derive/use them when including new model output?

**Comment by jetesdal** [comment]
Never mind, I think I found the scripts to generate these files:

https://github.com/radical-collaboration/facts/blob/development/modules/tlm/sterodynamics/2lmfit/regress_cmip6gte_vs_2lm_ohc.py
https://github.com/radical-collaboration/facts/blob/development/modules/tlm/sterodynamics/2lmfit/compare_2lm_tmix_cmip6gsat.py

I'll go ahead to try reproducing the files `scmpy2LM_RCMIP_CMIP6calpm_n18_expcoefs.nc` and `scmpy2LM_RCMIP_CMIP6calpm_n17_gsat_rmse.nc`. Meanwhile, I'll keep this issue open.

**Comment by bobkopp** [comment]
@jetesdal was this answered adequately?

**Comment by bobkopp** [comment]
@Timh37 could you please help?

**Comment by bobkopp** [comment]
@victor-malagon is working on a new module (ebm3) that has some improvements in terms of physical explainability (based on Yuan and Kopp 2020 multilayer pattern scaling, I think) but then I think also has the disadvantage that it can only use CMIP6 output that extends to 2300. He can chime in on the experience of a creating a whole new module here.

**Comment by victor-malagon** [comment]
@bobkopp The new ebm3 module selects CMIP6 zos simulations depending on the pyear_end (end of projection year) defined by the user:

- If pyear_end <= 2150, it selects all CMIP6 models that extend to 2100 (or beyond), and projects sterodynamics until 2150 (if needed) based on the multilayer pattern scaling. 

- If pyear_end > 2150, non-linearities become more pronounce in zos simulations. In this case, long-term emulation based on 2100 simulations is not ideal, as those non-linearities are not well represent in the training step of the multilayer pattern scaling approach. For this case we only select zos simulations extending to 2300. If pyear_end > 2300, sterodynamics is project using the multilayer approach. 

So the multilayer approach uses CMIP6 simulations that extend to 2300 only if pyear_end > 2150. For lower years all available simulations for given scenario are used.

**Comment by victor-malagon** [comment]
Worth also mentioning that ebm3 uses temperature output from the three layers in FaIR2, for both thermal expansion and sterodynamics. So this module needs both GSAT and two ocean temperatures coming from FaIR2. Using an alternative climate module for ebm3 should be possible as long as it produces three temperatures.

**Comment by bobkopp** [comment]
@victor-malagon Thanks, Victor! That approach makes sense.

It might also make sense to look at the joint distribution of calibration coefficients and consider whether they can be reasonably represented as a continuous multivariate probability distribution... we should discuss at some point.

**Comment by bobkopp** [comment]
@jetesdal If this has not been resolved yet, please follow up with @Timh37 directly.
