### ISSUE TITLE
Calculation of `OceanDynTECorr` in `tlm_sterodynamics_fit_oceandynamics.py`

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#331]
I am a bit confused how the correlation of ZOS and thermal expansion is defined in `tlm_sterodynamics_fit_oceandynamics.py `:

https://github.com/radical-collaboration/facts/blob/3ff08f91a8d8180b7058f8bcad884f0dc46dce53/modules/tlm/sterodynamics/tlm_sterodynamics_fit_oceandynamics.py#L200-L209

When testing the output, I see that dimensions of `OceanDynTECorr`
```python
np.shape(OceanDynTECorr)
```
is (300, 10) , with `years: 300` and `locations: 10`. This suggest that correlation is done across models for each time step. Instead, I thought that it should be temporal correlation between ZOS and thermal expansion. This would require the shape of `OceanDynTECorr` to be (21, 10), representing correlations per model per location.

Could you confirm if the intended behavior is to calculate the correlation across all models for each time point, or should it be across time per model and location?

**Comment by bobkopp** [comment]
This correlation is the correlation at each space-time point between uncertainty in global mean thermal expansion and uncertainty in DSL. See equation A1 in Kopp et al 2023.

**Comment by jetesdal** [comment]
OK got it. Thanks! Rereading Appendix 1 in Kopp et al 2023 also clarifies this point:

> One important difference is that this approach is recalibrated for each time step, whereas the Palmer et al. (2020) approach finds a single regression coefficient for a given GCM across time. A second is that the uncertainty not captured inthe characterized correlation is sampled, whereas in Palmeret al. (2020), all variance is assumed to be captured by thespread of regression coefficients across GCMs. The approachused here is more focused on the distributional characteris-tics across GCMs, as opposed to representing each individualGCM by a regression coefficient. As a consequence of these differences, the Kopp et al. (2014) approach loses a degree of traceability to individual GCMs, instead being focused on preserving the distributional properties assessed based on the ensemble.

In terms of assessing structural uncertainty in sterodynamics sea level, is there a plan to include the approach by [Palmer et al. (2020)](https://doi.org/10.1029/2019ef001413) or the pattern scaling described in, for example [Malagón-Santos et al. (2023)](https://doi.org/10.5194/os-19-499-2023)?

**Comment by bobkopp** [comment]
@victor-malagon can address this.

**Comment by victor-malagon** [comment]
What we showed in that study is that the way natural variability is removed can influence pattern scaling (and potentially other approaches to emulate DSL). I don't think it would be difficult to implement in FACTS, perhaps something to do in the near future. For now we would like to focus on improving long-term projections of DSL in FACTS by incorporating non-linearities, as in [Yuan and Kopp, 2021](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020MS002323), or a modification of it to include additional layers recently included in the FaIR simple climate model.

**Comment by jetesdal** [comment]
Hi @victor-malagon! Thanks for the clarification and the information! Just a quick follow-up. These long-term projections of DSL would still necessitate a new sterodynamics module that uses pattern scaling (as described for example in Yuan and Kopp, 2021), which the current `tlm` module does not do. That was my confusion. It is called `tlm` as "two-layer" but that is in connection with FaIR and the use of its OHC to derive the GMTSL. The distribution of DSL is mainly derived from the CMIP ensemble without using linear or nonlinear functions with a climate variable such as GSAT, or GMTSL. Right?

**Comment by bobkopp** [comment]
@jetesdal The distribution of DSL does not depend directly on GSAT, but it does preserve a correlation with GMTSL. See Appendix A of the FACTS manuscript.
