### ISSUE TITLE
In what way is the shape and distribution of sterodynamic sea level projections "baked in"?

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#332]
Upon discussion with @bobkopp, I am looking through the [tlm/sterodynamic](https://github.com/radical-collaboration/facts/tree/main/modules/tlm/sterodynamics) module code to better understand how the distribution of sterodynamic sea level projections can respond to different emission scenarios. Given the overall observation that the spread in the distribution of sterodynamic sea level seems to be fairly consistent across emissions, I want to understand whether this is something inherent in the underlying CMIP6 data or mainly how FACTS is generating the distribution.

Here is an outline of my observations. Please correct me if my interpretations are incorrect:

1. The output from `tlm/sterodynamic` for local sea level (`_localsl.nc`) is derived from a t-distribution:
https://github.com/radical-collaboration/facts/blob/3ff08f91a8d8180b7058f8bcad884f0dc46dce53/modules/tlm/sterodynamics/tlm_sterodynamics_postprocess.py#L172-L174

This suggests the assumption of a normal-like distribution with potential adjustments for degrees of freedom via `OceanDynDOF`, which is the number of available CMIP models (at a given location).

2. The distribution is centered around `condmean` and scaled by `condstd`, which are derived as
https://github.com/radical-collaboration/facts/blob/3ff08f91a8d8180b7058f8bcad884f0dc46dce53/modules/tlm/sterodynamics/tlm_sterodynamics_postprocess.py#L168-L169 

The calculation of `condmean` and `condstd` incorporates `OceanDynMean` and `OceanDynStd` which is derived as the mean and standard deviation across CMIP6 models, respectively:
https://github.com/radical-collaboration/facts/blob/3ff08f91a8d8180b7058f8bcad884f0dc46dce53/modules/tlm/sterodynamics/tlm_sterodynamics_fit_oceandynamics.py#L188-L189

Thus, `condstd` (i.e.,  the spread of the distribution given by `samps`) should vary by the emission scenario selected, as done in the [preprocessing](https://github.com/radical-collaboration/facts/blob/main/modules/tlm/sterodynamics/tlm_sterodynamics_preprocess_oceandynamics.py) step, in particular [IncludeCMIP6ZOSModels](https://github.com/radical-collaboration/facts/blob/3ff08f91a8d8180b7058f8bcad884f0dc46dce53/modules/tlm/sterodynamics/tlm_sterodynamics_preprocess_oceandynamics.py#L235).

The spread of `condstd` is further modified by `OceanDynTECorr`, but it's unclear how this adjustment impacts the overall spread of the distribution (see my question in #331)

**Questions**:
Does this confirm that the spread is not necessarily baked into the code? Also, I wonder if the assumption of normal distribution is potentially excluding long tails or skewness in the projections. Is this a valid assumption? Any clarification on how to interpret this would help me to better understand the implication of my current analysis with FACTS. Thanks!

**Comment by bobkopp** [comment]
It sounds like you're right that the code is recalibrating the conditional distributions for each SSP, so consistency across emissions scenarios is not baked in. 

The DSL distribution is (approximately) normal, conditional on thermal expansion, so you would not expect to get a fat tail for DSL except in association with a fat tail for thermal expansion.

**Comment by jetesdal** [comment]
Thanks @bobkopp for the clarification! That makes sense and helps me a lot in understanding the methodology. One follow up question: The calculation of **`condmean`**  for a given location ($r$) and year ($t$)
```python
condmean = OceanDynMean[od_year_ind,site_idx] +  OceanDynStd[od_year_ind,site_idx] * OceanDynTECorr[od_year_ind,site_idx] * ((tesamps-np.nanmean(tesamps, axis=0))/np.nanstd(tesamps, axis=0))[:,:,np.newaxis]
```
is basically equation A1 in Kopp et al 2023:
$$\overline{z_t(r)} + \sigma_t(r) \cdot k_t(r) \cdot \left( \frac{y_t - \overline{y_t}}{s_{y_t}} \right)$$
- $\overline{z_t(r)}$: Multi-model mean of DSL
- $\sigma_t(r)$: Multi-model standard deviation of DSL
- $k_t(r)$: Correlation between $y_t$ and $z_t$.
- $y_t$: Distribution of global mean thermosteric sea level (GMTSL) from the climate emulator with dimensions (`samples`, `years`)
- $\overline{y_t}$: Mean of GMTSL derived from the climate emulator
- $s_{y_t}$ Standard deviation of GMTSL derived from the climate emulator

`tesamps` ($y_t$) is derived from the OHC output of the climate emulator: 
```python
gte_samps = ohc_samps * expcoef_samps
```

As far as I can see,  there are three steps of randomization:

1. Since `tesamps` is a distribution of GMTSL with dimensions (`samples`, `years`), `condmean` will be a distribution with  dimensions (`samples`, `years`, `locations`).

2. If you then generate the DSL distribution as

```python
samps = t.ppf(quantile_samps[:,np.newaxis,np.newaxis],
              OceanDynDOF[np.newaxis,od_year_ind,site_idx]) * condstd + condmean
```

you add two distributions together.

3. Furthermore, we add the distribution of GMTSL to the DSL distribution.

```python
samps += tesamps[:,:,np.newaxis]
```

Is that a correct description of the relevant steps to get the final distribution of local sea level (`_localsl.nc`) from the tlm module? So if one recalculates the DSL distribution from FACTS output by removing  the global (`_globalsl.nc`) distribution, this should recover the t distribution with a conditional mean, given by equation A1 in Kopp et al 2023. Is it correct to say that this method randomizes the values in the three separate steps described above?

**Comment by bobkopp** [comment]
I'm not sure I understand what you mean by "steps of randomization", since randomization is not a reified thing in this process. Key steps are:

1. FAIR module calculates global OHC conditional upon emissions 
2. TLM project step calculates GMTE conditional upon OJC
3. TLM postprocess step calculates DSL conditional upon GMTE

The localsl netcdf file contains the sum of 2 and 3; if you want to recover 3, you subtract the globally netcdc file from the local file.
