### ISSUE TITLE
./modules/emulandice/AIS/../shared/emulandice_bundled_dependencies.tgz not found!

### ISSUE THREAD

**Issue by XinghanLiu2002** [radical-collaboration/facts#347]
I'm trying to install and use FACTS, following the quick start (https://fact-sealevel.readthedocs.io/en/latest/quickstart.html). 
But when I executed the command `python3 runFACTS.py test` , I got an error 
`File "/work/home/xinghan/facts/FACTS.py", line 162, in GenerateTask
    raise(FileNotFoundError(pipe_name + "." + stage_name + ": upload_and_extract_input_data: " + this_file + " not found!"))
FileNotFoundError: test.emuAIS.emulandice.AIS.project: upload_and_extract_input_data: ./modules/emulandice/AIS/../shared/emulandice_bundled_dependencies.tgz not found!`
 I referred to a previous comment in my search for a workaround.
![8789148eeff109728b1610d79b4a5e3](https://github.com/user-attachments/assets/f2f176d7-7a36-4a4b-95fd-03fef66ad821)
I followed the steps above to debug, but I still got the same error.
It seems that there is a need to create an environment in R, so I want to know how to go about it.

**Comment by bobkopp** [comment]
Have you followed the steps in the quick start documentation necessary to run emulandice? This file should be created by emulandice_config.sh.

**Comment by XinghanLiu2002** [comment]
Thank you for your reply@bobkopp. I just checked the process and found that it was my R environment that was wrong, but after fixing the previous problem, a new error appeared:
`$ python3 runFACTS.py test
EnTK session: re.session.login01.xinghan.019994.0002
Creating AppManager
Setting up ZMQ queues                                                         ok
AppManager initialized                                                        ok
Validating and assigning resource manager                                     ok
****** STEP: climate_step ******
Setting up ZMQ queues                                                        n/a
All components terminated
Traceback (most recent call last):
  File "/work/home/xinghan/miniconda3/envs/ve3/lib/python3.12/site-packages/radical/entk/appman/appmanager.py", line 459, in run
    self._rmgr.submit_resource_request()
  File "/work/home/xinghan/miniconda3/envs/ve3/lib/python3.12/site-packages/radical/entk/execman/rp/resource_manager.py", line 225, in submit_resource_request
    self._pilot.wait([rp.PMGR_ACTIVE, rp.DONE, rp.FAILED, rp.CANCELED])
  File "/work/home/xinghan/miniconda3/envs/ve3/lib/python3.12/site-packages/radical/pilot/pilot.py", line 615, in wait
    time.sleep(0.1)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/home/xinghan/facts/runFACTS.py", line 193, in <module>
    run_experiment(args.edir, args.debug, args.alt_id, resourcedir=args.resourcedir, makeshellscript = args.shellscript, globalopts = args.global_options)
  File "/work/home/xinghan/facts/runFACTS.py", line 86, in run_experiment
    amgr.run()
  File "/work/home/xinghan/miniconda3/envs/ve3/lib/python3.12/site-packages/radical/entk/appman/appmanager.py", line 485, in run
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError`

 When I tried to run it using another way `sbatch runtest.sh`  ，I still got the error.

The contents of the script are as follows：
`#!/bin/bash
#SBATCH --partition=xahcnormal    # Partition (job queue)
#SBATCH --job-name=facts          # Assign a short name to your job
#SBATCH --nodes=1                 # Number of nodes you require
#SBATCH --ntasks-per-node=24      # Total # of tasks across all nodes
#SBATCH --time=05:00:00           # Total run time limit (HH:MM:SS)
#SBATCH --output=slurm.%N.%j.out  # STDOUT output file
#SBATCH --error=slurm.%N.%j.err   # STDERR output file (optional)

source ~/miniconda3/bin/activate ve3 

radical-stack

export RADICAL_LOG_LVL="DEBUG"
export RADICAL_PROFILE="TRUE"
python3 ./runFACTS.py test`
Could you give me some suggestions about this？

**Comment by bobkopp** [comment]
If you are trying to run on a HPC system, you may need some assistance in configuring the RADICAL stack. If this is the case, please ask @mturilli

**Comment by XinghanLiu2002** [comment]
Thank you very much for your suggestions and support! @bobkopp 
And the platform I am trying to run FACTS on is Sugon HPC system @mturilli
