### ISSUE TITLE
Is there an easy way to parse pipeline.yml into a shell script?

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#52]
For many modules, a straightforward way of testing is to run on local resources at a limited number of space-time points without the EnTK overhead and comparing to target values. Greg effectively did this for the IPCC AR6 execution by manually creating shell scripts (and manually comparing to target values), but it seems like there should be a straightforward way of generating such scripts from pipeline.yml. Does such a method exist, or could one of the RADICAL team help with its creation?

**Comment by bobkopp** [comment]
Eg see scripts-ar6/submit_components_full_sample_update/ for examples of shell scripts Greg created to manually call components. For testing purposes, I'd love an automated way to create similar scripts that don't go through the scheduler and instead creates a workspace in a target directory (eg in /scratch) and runs the commands specified by pipeline.yml (ie extracting the data file and executing the script). 

For the current pipeline, this includes installing modules by pip, so we might need to also create a temporary conda environment, or comment that bit out and assume the user will take care of the environment 

But, in any case, I think many module developers will want to be able to do quick tests without going through EnTK - would be create to facilitate producing shell scripts that are aligned with what pipeline.yml calls for.

**Comment by andre-merzky** [comment]
> Is there an easy way to parse pipeline.yml into a shell script?

There is no existing tool to provide that functionality, but we should be able to come up with a quick implementation.

> I created an example in ...

Thanks for that, that's a great starting point!

**Comment by bobkopp** [comment]
I created test scripts of the sort I have in mind, based on the slurm submission scripts Greg was using, eg https://github.com/radical-collaboration/facts/blob/main/modules/ar5/icesheets/test/run_test.sh

**Comment by bobkopp** [comment]
Andre, if you haven't started on this yet, I have an idea I'd like to try, so please postpone for the moment.

**Comment by andre-merzky** [comment]
All right!

**Comment by bobkopp** [comment]
Ok, I have a solution for this that seems reasonable to me, using the yq package. There are enough things in the pipeline.yml that differ for testing purposes that the only thing I'm extracting from pipeline.yml is the name of the scripts. (If I were more clever, I would also be extracting the names of the stages, but couldn't figure that out.)

... see https://github.com/radical-collaboration/facts/tree/main/modules/ar5/icesheets/test for an example, and https://github.com/radical-collaboration/facts/tree/main/scripts/moduletest
