### ISSUE TITLE
For testing purposes, allow config.yml to be translated into a shell script

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#81]
For testing purposes (and potentially, with lighter weight modules, application) it'd be helpful to be able to parse the experiment config.yml into a shell script that can be separately executed. Does it make more sense to implement this functionality in FACTS.py or AppManager?

**Comment by andre-merzky** [comment]
I would suggest to do that in `FACTS.py` or in a separate module.  ENTK's `AppManager` is not supposed to host logic which depends on application details - the structure of `config.yml` would be such an application detail.

**Comment by bobkopp** [comment]
That’s a reasonable approach, but all the FACTS.py parsing of config.yml does is create a set of nested pipelines — turning a pipeline into a shell script seems like it might be an appropriate EnTK role?
________________________________

**Comment by andre-merzky** [comment]
Ah, sorry, I misunderstood.  That might indeed be in scope.  Let me discuss that with our group.  Thanks for clarifying!

**Comment by bobkopp** [comment]
Merged into https://github.com/radical-collaboration/facts/issues/148
