### ISSUE TITLE
Create quickstart example for users running on a new platform

### ISSUE THREAD

**Issue by bobkopp** [radical-collaboration/facts#93]
We need a quickstart guide for users seeking to run FACTS on their own hardware. Simplistically, for users seeking to run on localhost, with clear pointers as to how to set up to run on a local cluster.

**Comment by andre-merzky** [comment]
summary for using virtualenv:
```sh
git clone git@github.com:radical-collaboration/facts.git
cd facts
git checkout fix/workflow_assignment

python3 -m venv ve3
. ve3/bin/activate
pip install --upgrade setuptools pip wheel
pip install radical.entk
pip install numpy scipy netCDF4 pyyaml matplotlib h5py yq

vim experiments/temp_exp/config.yml
  -> replace 'localhost' with 'amarel'
rm -rf test
mkdir test
cp -r experiments/temp_exp/* test
python3 runFACTS.py test
```

summary for using conda:
```sh
$ conda create -n facts
$ conda activate facts
$ conda install -c conda-forge radical.entk
$ conda install numpy scipy netCDF4 pyyaml matplotlib h5py yq
$ git clone git@github.com:radical-collaboration/facts.git
$ cd facts/modules-data
$ ln -s /projects/kopp/facts-dev/modules-data/*.tgz .
$ cd ..
$ mkdir test
$ cp -r experiments/temp_exp test
$ emacs test/config.yml
  -> replace 'localhost' with 'amarel'
$ python runFACTS.py test
```

**Comment by bobkopp** [comment]
Can we add more guidance for a user trying to run FACTS (1) without root privileges and (2) without relying on a distant server run by RADICAL? I think the most ready solution might rely on running the RabbitMQ and MongoDB in a Singularity instance with network virtualization and only the lo interface  -- not ideal, but I'm getting stuck with figuring out other options for (for example)  running on Amarel without relying on RADICAL servers.

**Comment by bobkopp** [comment]
Merged into https://github.com/radical-collaboration/facts/issues/114
