### ISSUE TITLE
fix `setup.py`

### ISSUE THREAD

**Issue by andre-merzky** [radical-collaboration/facts#96]
`setup.py` does not install anything at the moment and is in fact still tailored towards python2.  It should be fixed to install:

  - `FACTS.py` as python module
  - `runFACTS.py` as executable script in `.../bin/`
  - `modules/*` in `.../shared/facts`
  - resource configs somewhere in `.../shared` so that the code can pick them up as needed

**Comment by andre-merzky** [comment]
While implementing the above I realized that the `modules/` tree contains symbolic links which point to non-existing files.  Those data files are expected to be provided by the end user.  I think this is a somewhat reasonable approach, given the size of the data files - but alas the Python setuptools don't  support the installation of symlinks.  It is also somewhat difficult for users to place the data later into the Python share tree - for example, they may not even have access to that tree.

How should we handle this?  Should we maybe not install the `modules/` tree at all?  Should we not install the symlinks, but everything else?  What is the user expected to do in that case?

@bobkopp : please advise what your preferred approach would be.

**Comment by bobkopp** [comment]
Good question, I would take some guidance here. The symlinks are important for running modules outside the EnTK framework (the moduletest.sh scripts rely on them) but shouldn't actually be needed when running within FACTS.

For the longer term, modules should be installable separately from the FACTS Manager, but we do need to provide a way of getting the users the modules.

**Comment by bobkopp** [comment]
Bumping packaging questions to post-submission

**Comment by bobkopp** [comment]
Merge into https://github.com/radical-collaboration/facts/issues/145
