### ISSUE TITLE
Allow users to overwrite resource config settings

### ISSUE THREAD

**Issue by andre-merzky** [radical-collaboration/facts#98]
> Resource*.yml files currently live in the experiement directory, but these ought to live in a central location (e.g., facts/resources) rather than having to be copied from experiment to experiment

>  I would suggest to fix setup.py and to have some proper installation which then could include the resource config files.  The code can then pick up those config files from the installation.   We do something similar for resource configs in our code - but also allow the user to add config files or to overwrite settings in ~/.facts/ if needed.

**Comment by bobkopp** [comment]
For 1.0, I think it's fine if we just have FACTS look in the resources/ directory rather than the experiment directory for the resource files.

**Comment by bobkopp** [comment]
https://github.com/radical-collaboration/facts/pull/116 relocates files out of experiment directory
